[env:rp2040_zero]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower
monitor_speed = 115200
build_src_filter = -<*> +<main.cpp>

lib_deps =
    FastLED
    milesburton/DallasTemperature
    paulstoffregen/OneWire
